/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package imaging;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Transform implements org.apache.thrift.TEnum {
  UPDOWN(1),
  LEFTRIGHT(2),
  TRANSPOSE(3),
  ROTATE90CW(4),
  ROTATE90CCW(5),
  ROTATE180(6),
  XGRADIENT(7);

  private final int value;

  private Transform(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Transform findByValue(int value) { 
    switch (value) {
      case 1:
        return UPDOWN;
      case 2:
        return LEFTRIGHT;
      case 3:
        return TRANSPOSE;
      case 4:
        return ROTATE90CW;
      case 5:
        return ROTATE90CCW;
      case 6:
        return ROTATE180;
      case 7:
        return XGRADIENT;
      default:
        return null;
    }
  }
}
