Import('env')

import sys

THRIFT="/usr/local/thrift-0.6.1/"
LIBEVENT="/usr/local/libevent-2.0.12/"
SRC_ROOT = env['SRC_ROOT']

gensrc = [
     SRC_ROOT + 'gen-cpp/shared_constants.cpp',
     SRC_ROOT + 'gen-cpp/shared_types.cpp',
     SRC_ROOT + 'gen-cpp/tutorial_constants.cpp',
     SRC_ROOT + 'gen-cpp/tutorial_types.cpp',
     SRC_ROOT + 'gen-cpp/Calculator.cpp',
     SRC_ROOT + 'gen-cpp/SharedService.cpp',
]

cpppath = [
    SRC_ROOT + "gen-cpp",
    THRIFT + 'include/thrift',
    LIBEVENT + 'include',
]

libpath = [
    THRIFT + 'lib',
    LIBEVENT + 'lib',
]

libs = [
    'thrift',
    'thriftnb',
    'event',
]

appclient = env.AbbProg(progname="client", sources=gensrc + [SRC_ROOT + 'CppClient.cpp',],
                  includes=cpppath, libpath=libpath, libs=libs)
appserver = env.AbbProg(progname="server", sources=gensrc + [SRC_ROOT + 'CppServer.cpp',],
                  includes=cpppath, libpath=libpath, libs=libs)

target = Alias('apps', [client, server])

Return("target")
