/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef imaging_CONSTANTS_H
#define imaging_CONSTANTS_H

#include "imaging_types.h"

namespace imaging {

class imagingConstants {
 public:
  imagingConstants();

};

extern const imagingConstants g_imaging_constants;

} // namespace

#endif
