/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Imaging_H
#define Imaging_H

#include <transport/TBufferTransports.h>
#include <tr1/functional>
namespace apache { namespace thrift { namespace async {
class TAsyncChannel;
}}}
#include <TProcessor.h>
#include <async/TAsyncProcessor.h>
#include "imaging_types.h"

namespace imaging {

class ImagingIf {
 public:
  virtual ~ImagingIf() {}
  virtual void mandelbrot(std::string& _return, const int32_t w, const int32_t h) = 0;
  virtual void transform(std::string& _return, const Transform::type t, const std::string& img) = 0;
};

class ImagingNull : virtual public ImagingIf {
 public:
  virtual ~ImagingNull() {}
  void mandelbrot(std::string& /* _return */, const int32_t /* w */, const int32_t /* h */) {
    return;
  }
  void transform(std::string& /* _return */, const Transform::type /* t */, const std::string& /* img */) {
    return;
  }
};

typedef struct _Imaging_mandelbrot_args__isset {
  _Imaging_mandelbrot_args__isset() : w(false), h(false) {}
  bool w;
  bool h;
} _Imaging_mandelbrot_args__isset;

class Imaging_mandelbrot_args {
 public:

  Imaging_mandelbrot_args() : w(0), h(0) {
  }

  virtual ~Imaging_mandelbrot_args() throw() {}

  int32_t w;
  int32_t h;

  _Imaging_mandelbrot_args__isset __isset;

  void __set_w(const int32_t val) {
    w = val;
  }

  void __set_h(const int32_t val) {
    h = val;
  }

  bool operator == (const Imaging_mandelbrot_args & rhs) const
  {
    if (!(w == rhs.w))
      return false;
    if (!(h == rhs.h))
      return false;
    return true;
  }
  bool operator != (const Imaging_mandelbrot_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Imaging_mandelbrot_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Imaging_mandelbrot_pargs {
 public:


  virtual ~Imaging_mandelbrot_pargs() throw() {}

  const int32_t* w;
  const int32_t* h;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Imaging_mandelbrot_result__isset {
  _Imaging_mandelbrot_result__isset() : success(false), ouch(false) {}
  bool success;
  bool ouch;
} _Imaging_mandelbrot_result__isset;

class Imaging_mandelbrot_result {
 public:

  Imaging_mandelbrot_result() : success("") {
  }

  virtual ~Imaging_mandelbrot_result() throw() {}

  std::string success;
  InvalidOperation ouch;

  _Imaging_mandelbrot_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  void __set_ouch(const InvalidOperation& val) {
    ouch = val;
  }

  bool operator == (const Imaging_mandelbrot_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const Imaging_mandelbrot_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Imaging_mandelbrot_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Imaging_mandelbrot_presult__isset {
  _Imaging_mandelbrot_presult__isset() : success(false), ouch(false) {}
  bool success;
  bool ouch;
} _Imaging_mandelbrot_presult__isset;

class Imaging_mandelbrot_presult {
 public:


  virtual ~Imaging_mandelbrot_presult() throw() {}

  std::string* success;
  InvalidOperation ouch;

  _Imaging_mandelbrot_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Imaging_transform_args__isset {
  _Imaging_transform_args__isset() : t(false), img(false) {}
  bool t;
  bool img;
} _Imaging_transform_args__isset;

class Imaging_transform_args {
 public:

  Imaging_transform_args() : img("") {
  }

  virtual ~Imaging_transform_args() throw() {}

  Transform::type t;
  std::string img;

  _Imaging_transform_args__isset __isset;

  void __set_t(const Transform::type val) {
    t = val;
  }

  void __set_img(const std::string& val) {
    img = val;
  }

  bool operator == (const Imaging_transform_args & rhs) const
  {
    if (!(t == rhs.t))
      return false;
    if (!(img == rhs.img))
      return false;
    return true;
  }
  bool operator != (const Imaging_transform_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Imaging_transform_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Imaging_transform_pargs {
 public:


  virtual ~Imaging_transform_pargs() throw() {}

  const Transform::type* t;
  const std::string* img;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Imaging_transform_result__isset {
  _Imaging_transform_result__isset() : success(false), ouch(false) {}
  bool success;
  bool ouch;
} _Imaging_transform_result__isset;

class Imaging_transform_result {
 public:

  Imaging_transform_result() : success("") {
  }

  virtual ~Imaging_transform_result() throw() {}

  std::string success;
  InvalidOperation ouch;

  _Imaging_transform_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  void __set_ouch(const InvalidOperation& val) {
    ouch = val;
  }

  bool operator == (const Imaging_transform_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const Imaging_transform_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Imaging_transform_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Imaging_transform_presult__isset {
  _Imaging_transform_presult__isset() : success(false), ouch(false) {}
  bool success;
  bool ouch;
} _Imaging_transform_presult__isset;

class Imaging_transform_presult {
 public:


  virtual ~Imaging_transform_presult() throw() {}

  std::string* success;
  InvalidOperation ouch;

  _Imaging_transform_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ImagingClient : virtual public ImagingIf {
 public:
  ImagingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ImagingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void mandelbrot(std::string& _return, const int32_t w, const int32_t h);
  void send_mandelbrot(const int32_t w, const int32_t h);
  void recv_mandelbrot(std::string& _return);
  void transform(std::string& _return, const Transform::type t, const std::string& img);
  void send_transform(const Transform::type t, const std::string& img);
  void recv_transform(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ImagingProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<ImagingIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (ImagingProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_mandelbrot(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_transform(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ImagingProcessor(boost::shared_ptr<ImagingIf> iface) :
    iface_(iface) {
    processMap_["mandelbrot"] = &ImagingProcessor::process_mandelbrot;
    processMap_["transform"] = &ImagingProcessor::process_transform;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~ImagingProcessor() {}
};

class ImagingMultiface : virtual public ImagingIf {
 public:
  ImagingMultiface(std::vector<boost::shared_ptr<ImagingIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ImagingMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ImagingIf> > ifaces_;
  ImagingMultiface() {}
  void add(boost::shared_ptr<ImagingIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void mandelbrot(std::string& _return, const int32_t w, const int32_t h) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->mandelbrot(_return, w, h);
        return;
      } else {
        ifaces_[i]->mandelbrot(_return, w, h);
      }
    }
  }

  void transform(std::string& _return, const Transform::type t, const std::string& img) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->transform(_return, t, img);
        return;
      } else {
        ifaces_[i]->transform(_return, t, img);
      }
    }
  }

};

class ImagingCobClient;

class ImagingCobClIf {
 public:
  virtual ~ImagingCobClIf() {}
  virtual void mandelbrot(std::tr1::function<void(ImagingCobClient* client)> cob, const int32_t w, const int32_t h) = 0;
  virtual void transform(std::tr1::function<void(ImagingCobClient* client)> cob, const Transform::type t, const std::string& img) = 0;
};

class ImagingCobSvIf {
 public:
  virtual ~ImagingCobSvIf() {}
  virtual void mandelbrot(std::tr1::function<void(std::string const& _return)> cob, std::tr1::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const int32_t w, const int32_t h) = 0;
  virtual void transform(std::tr1::function<void(std::string const& _return)> cob, std::tr1::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const Transform::type t, const std::string& img) = 0;
};

class ImagingCobSvNull : virtual public ImagingCobSvIf {
 public:
  virtual ~ImagingCobSvNull() {}
  void mandelbrot(std::tr1::function<void(std::string const& _return)> cob, std::tr1::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const int32_t /* w */, const int32_t /* h */) {
    std::string _return = "";
    return cob(_return);
  }
  void transform(std::tr1::function<void(std::string const& _return)> cob, std::tr1::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const Transform::type /* t */, const std::string& /* img */) {
    std::string _return = "";
    return cob(_return);
  }
};

class ImagingCobClient : virtual public ImagingCobClIf {
 public:
  ImagingCobClient(boost::shared_ptr< ::apache::thrift::async::TAsyncChannel> channel, ::apache::thrift::protocol::TProtocolFactory* protocolFactory) :
    channel_(channel),
    itrans_(new ::apache::thrift::transport::TMemoryBuffer()),
    otrans_(new ::apache::thrift::transport::TMemoryBuffer()),
    piprot_(protocolFactory->getProtocol(itrans_)),
    poprot_(protocolFactory->getProtocol(otrans_)) {
    iprot_ = piprot_.get();
    oprot_ = poprot_.get();
  }
  boost::shared_ptr< ::apache::thrift::async::TAsyncChannel> getChannel() {
    return channel_;
  }
  virtual void completed__(bool /* success */) {}
  void mandelbrot(std::tr1::function<void(ImagingCobClient* client)> cob, const int32_t w, const int32_t h);
  void send_mandelbrot(const int32_t w, const int32_t h);
  void recv_mandelbrot(std::string& _return);
  void transform(std::tr1::function<void(ImagingCobClient* client)> cob, const Transform::type t, const std::string& img);
  void send_transform(const Transform::type t, const std::string& img);
  void recv_transform(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::async::TAsyncChannel> channel_;
  boost::shared_ptr< ::apache::thrift::transport::TMemoryBuffer> itrans_;
  boost::shared_ptr< ::apache::thrift::transport::TMemoryBuffer> otrans_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ImagingAsyncProcessor : virtual public ::apache::thrift::TAsyncProcessor {
 protected:
  boost::shared_ptr<ImagingCobSvIf> iface_;
  virtual void process_fn(std::tr1::function<void(bool ok)> cob, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid);
 private:
  std::map<std::string, void (ImagingAsyncProcessor::*)(std::tr1::function<void(bool ok)>, int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*)> processMap_;
  void process_mandelbrot(std::tr1::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_mandelbrot(std::tr1::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const std::string& _return);
  void throw_mandelbrot(std::tr1::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
  void process_transform(std::tr1::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void return_transform(std::tr1::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, const std::string& _return);
  void throw_transform(std::tr1::function<void(bool ok)> cob, int32_t seqid, ::apache::thrift::protocol::TProtocol* oprot, void* ctx, ::apache::thrift::TDelayedException* _throw);
 public:
  ImagingAsyncProcessor(boost::shared_ptr<ImagingCobSvIf> iface) :
    iface_(iface) {
    processMap_["mandelbrot"] = &ImagingAsyncProcessor::process_mandelbrot;
    processMap_["transform"] = &ImagingAsyncProcessor::process_transform;
  }

  virtual void process(std::tr1::function<void(bool ok)> cob, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot);
  virtual ~ImagingAsyncProcessor() {}
};

} // namespace

#endif
