/**
 * Autogenerated by Thrift Compiler (0.7.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "imaging_constants.h"

namespace imaging {

const imagingConstants g_imaging_constants;

imagingConstants::imagingConstants() {
}

} // namespace

