// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Imaging.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace imaging;

class ImagingHandler : virtual public ImagingIf {
 public:
  ImagingHandler() {
    // Your initialization goes here
  }

  void mandelbrot(std::string& _return, const int32_t w, const int32_t h) {
    // Your implementation goes here
    printf("mandelbrot\n");
  }

  void transform(std::string& _return, const Transform::type t, const std::string& img) {
    // Your implementation goes here
    printf("transform\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ImagingHandler> handler(new ImagingHandler());
  shared_ptr<TProcessor> processor(new ImagingProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

