/**
 * Autogenerated by Thrift Compiler (0.7.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package imaging {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public interface Imaging {

    /**
     * A method definition looks like C code. It has a return type, arguments,
     * and optionally a list of exceptions that it may throw. Note that argument
     * lists and exception lists are specified using the exact same syntax as
     * field lists in struct or exception definitions.
     * 
     * @param w
     * @param h
     */
    //function onError(Error):void;
    //function onSuccess(ByteArray):void;
    function mandelbrot(w:int, h:int, onError:Function, onSuccess:Function):void;

    //function onError(Error):void;
    //function onSuccess(ByteArray):void;
    function transform(t:int, img:ByteArray, onError:Function, onSuccess:Function):void;

  }

}
